name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        # Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: # optional
        # Name of the Azure Web App
        app-name: 
        # Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: # optional, default is .
        # Enter an existing Slot other than the Production slot
        slot-name: # optional, default is production
